PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?s ?l
WHERE {
  {?s a owl:Class . } UNION {?s a owl:DatatypeProperty .} 
      UNION {?s a owl:ObjectProperty . } UNION {?s a owl:AnnotationProperty .}
  OPTIONAL { ?s rdfs:label ?l }
  }
ORDER BY ?s