PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?parent_label ?label

WHERE {	
    ?uri a owl:Class .
    {?uri rdfs:subClassOf obo:ERO_0000004 .} UNION {?parent rdfs:subClassOf obo:ERO_0000004 . ?uri rdfs:subClassOf ?parent . }
    UNION {?grand_parent rdfs:subClassOf obo:ERO_00000004 . ?parent rdfs:subClassOf ?grand_parent . ?uri rdfs:subClassOf ?parent .}
    ?uri rdfs:subClassOf ?parent .
    ?uri rdfs:label ?label .
    ?parent rdfs:label ?parent_label .
}
ORDER BY ?parent_label ?label
