PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?type ?uri
    (GROUP_CONCAT(DISTINCT ?label; SEPARATOR="|") AS ?labels)
    (GROUP_CONCAT(DISTINCT ?definition; SEPARATOR="|") AS ?definitions)
    (GROUP_CONCAT(DISTINCT ?editor_note; SEPARATOR="|") AS ?editor_notes)
    (GROUP_CONCAT(DISTINCT ?example; SEPARATOR="|") AS ?examples)
	(GROUP_CONCAT(DISTINCT ?status; SEPARATOR="|") AS ?statuses)
	(GROUP_CONCAT(DISTINCT ?human_friendly_name; SEPARATOR="|") AS ?human_friendly_names)
	(GROUP_CONCAT(DISTINCT ?name_of_editor; SEPARATOR="|") AS ?name_of_editors)
	(GROUP_CONCAT(DISTINCT ?alternative_name; SEPARATOR="|") AS ?alternative_names)
	(GROUP_CONCAT(DISTINCT ?citation; SEPARATOR="|") AS ?citations)

WHERE {
	{	
		?uri a owl:Class .
		FILTER(regex(str(?uri), "^[a-zA-Z]"))
    	BIND("C" AS ?type)
		OPTIONAL { ?uri rdfs:label ?label }
		OPTIONAL { ?uri obo:IAO_0000115 ?definition }
		OPTIONAL { ?uri obo:IAO_0000116 ?editor_note }
		OPTIONAL { ?uri obo:IAO_0000112 ?example }
		OPTIONAL { ?uri obo:IAO_0000114 ?status }
		OPTIONAL { ?uri obo:IAO_0000111 ?human_friendly_name }
		OPTIONAL { ?uri obo:IAO_0000117 ?name_of_editor }
		OPTIONAL { ?uri obo:IAO_0000118 ?alternative_name }
		OPTIONAL { ?uri obo:IAO_0000119 ?citation }
	}
    UNION
    {	
    	?uri a owl:ObjectProperty .
    	BIND("O" AS ?type)
		OPTIONAL { ?uri rdfs:label ?label }
		OPTIONAL { ?uri obo:IAO_0000115 ?definition }
		OPTIONAL { ?uri obo:IAO_0000116 ?editor_note }
		OPTIONAL { ?uri obo:IAO_0000112 ?example }
		OPTIONAL { ?uri obo:IAO_0000114 ?status }
		OPTIONAL { ?uri obo:IAO_0000111 ?human_friendly_name }
		OPTIONAL { ?uri obo:IAO_0000117 ?name_of_editor }
		OPTIONAL { ?uri obo:IAO_0000118 ?alternative_name }
		OPTIONAL { ?uri obo:IAO_0000119 ?citation }   
    }
    UNION
    {	
    	?uri a owl:DatatypeProperty .
    	BIND("D" AS ?type)
		OPTIONAL { ?uri rdfs:label ?label }
		OPTIONAL { ?uri obo:IAO_0000115 ?definition }
		OPTIONAL { ?uri obo:IAO_0000116 ?editor_note }
		OPTIONAL { ?uri obo:IAO_0000112 ?example }
		OPTIONAL { ?uri obo:IAO_0000114 ?status }
		OPTIONAL { ?uri obo:IAO_0000111 ?human_friendly_name }
		OPTIONAL { ?uri obo:IAO_0000117 ?name_of_editor }
		OPTIONAL { ?uri obo:IAO_0000118 ?alternative_name }
		OPTIONAL { ?uri obo:IAO_0000119 ?citation }    
    }
    UNION
    {	
    	?uri a owl:AnnotationProperty .
    	BIND("A" AS ?type)
		OPTIONAL { ?uri rdfs:label ?label }
		OPTIONAL { ?uri obo:IAO_0000115 ?definition }
		OPTIONAL { ?uri obo:IAO_0000116 ?editor_note }
		OPTIONAL { ?uri obo:IAO_0000112 ?example }
		OPTIONAL { ?uri obo:IAO_0000114 ?status }
		OPTIONAL { ?uri obo:IAO_0000111 ?human_friendly_name }
		OPTIONAL { ?uri obo:IAO_0000117 ?name_of_editor }
		OPTIONAL { ?uri obo:IAO_0000118 ?alternative_name }
		OPTIONAL { ?uri obo:IAO_0000119 ?citation }    
    }
}
GROUP BY ?type ?uri
ORDER BY ?type ?uri
