PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?uri ?label

WHERE {
    ?uri a owl:Class .
    ?uri rdfs:label ?label .
    ?uri rdfs:subClassOf obo:BFO_0000023 .
}
ORDER BY ?uri ?label
